### ISSUE TITLE
about $firstName

### ISSUE THREAD

**Issue by johnwonder** [lerencao/guides-to-scala-book#3]
in chp2-extracting-sequences.md there is $firstName,but in my REPL it can not display $firstName as the actual value，can you tell me the reason? is it because of the scala version's problem?

**Comment by nanne007** [comment]
I thinks it should be `s"my first name is $firstname"` in scala 2.11.

Thanks for the feedback.

**Comment by nanne007** [comment]
Fixed. Closing now.
